# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipesDB' do
   pod 'RxSwift', '~>5'
   pod 'RxCocoa', '~>5'
   pod 'Alamofire'
   pod 'AlamofireImage'
 
  # Pods for RecipesDB

  target 'RecipesDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecipesDBUITests' do
    # Pods for testing
  end

end
